In [1]:
# installations for colab
!pip install transformers accelerate torch huggingface_hub datasets emoji

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.48.3)
Requirement already satisfied: accelerate in /usr/local/lib/python3.11/dist-packages (1.3.0)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (2.5.1+cu124)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.11/dist-packages (0.28.1)
Collecting datasets
  Downloading datasets-3.3.2-py3-none-any.whl.metadata (19 kB)
Collecting emoji
  Downloading emoji-2.14.1-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.11/dist-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch) (2024.10.0)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.13)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.5.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.1 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 76.4 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 35.3 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 33.4 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.0 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.5 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 37.4 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.4 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 3.6 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 28.2 MB/s eta 0:00:00
Downloading datasets-3.3.2-py3-none-any.whl (485 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 30.6 MB/s eta 0:00:00
Downloading emoji-2.14.1-py3-none-any.whl (590 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 590.6/590.6 kB 40.5 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 9.3 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 11.9 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 16.6 MB/s eta 0:00:00
Installing collected packages: xxhash, nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, emoji, dill, nvidia-cusparse-cu12, nvidia-cudnn-cu12, multiprocess, nvidia-cusolver-cu12, datasets
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed datasets-3.3.2 dill-0.3.8 emoji-2.14.1 multiprocess-0.70.16 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 xxhash-3.5.0

In [ ]:
import pandas as pd

# df_tweets = pd.read_csv("./SA_data/twitter_dataset.csv")
# df_tweets.head()

In [ ]:
len(df_tweets)

3142403

In [ ]:
#df_tweets["sentiment"] = df_tweets["sentiment"].replace({0.0 : "negative", 1.0 : "positive", 2.0 : "neutral"})
df_tweets.head()

   Unnamed: 0                                              tweet  sentiment
0           0  is upset that he can't update his Facebook by ...        0.0
1           1  @Kenichan I dived many times for the ball. Man...        0.0
2           2    my whole body feels itchy and like its on fire         0.0
3           3  @nationwideclass no, it's not behaving at all....        0.0
4           4                      @Kwesidei not the whole crew         0.0

In [ ]:
df_tweets.sentiment.value_counts()
# 0 = negative, 1 = positive, 2 = neutral

sentiment
0.0    1570067
1.0    1561529
2.0      10725
Name: count, dtype: int64

In [ ]:
df_tweets.dropna(inplace=True)

# NLPtown BERT-Base-Sentiment

In [ ]:
# model built for product reviews (from 1 to 5)
tokenizer = AutoTokenizer.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

model = AutoModelForSequenceClassification.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

c:\Users\hausb\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:159: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\hausb\.cache\huggingface\hub\models--nlptown--bert-base-multilingual-uncased-sentiment. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
c:\Users\hausb\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

In [ ]:
tokens = tokenizer.encode('It was good but couldve been better. Great', return_tensors='pt')
result = model(tokens)

In [ ]:
result.logits

tensor([[-2.7768, -1.2353,  1.4419,  1.9804,  0.4584]],
       grad_fn=<AddmmBackward0>)

# BerTweet Sentiment Analysis

In [56]:
# using bertweet-sentiment analysis
# https://huggingface.co/finiteautomata/bertweet-base-sentiment-analysis

from transformers import AutoTokenizer, AutoModelForSequenceClassification
bertweet_t = AutoTokenizer.from_pretrained("finiteautomata/bertweet-base-sentiment-analysis")

bertweet = AutoModelForSequenceClassification.from_pretrained(
    "finiteautomata/bertweet-base-sentiment-analysis",
    device_map="auto",
    num_labels=3)

tokenizer_config.json:   0%|          | 0.00/338 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/843k [00:00<?, ?B/s]

bpe.codes:   0%|          | 0.00/1.08M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/167 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/949 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/540M [00:00<?, ?B/s]

In [ ]:
import torch

def sentiment_score(text, tokenizer, model):
    tokens = tokenizer.encode(text, return_tensors='pt')
    result = model(tokens)
    return int(torch.argmax(result.logits))

In [49]:
import torch

def bert_pred(model, tokenizer, df, text_col):

    # moving model to GPU and setting it to evaluation-mode
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(model.device)
    model.eval()

    batch_size = 32
    num_batches = len(df) // batch_size + 1
    predictions = []

    for i in range(num_batches):
        start_idx = i * batch_size
        end_idx = min((i + 1) * batch_size, len(df))
        batch_tokens = tokenizer(df[text_col][start_idx:end_idx].tolist(),
                                 padding=True, truncation=True, return_tensors="pt", max_length=512)
        batch_tokens = {key: value.to(device) for key, value in batch_tokens.items()}

        with torch.no_grad():
            outputs = model(**batch_tokens)
            batch_predictions = torch.argmax(outputs.logits, dim=-1)
            predictions.extend(batch_predictions.cpu().numpy())

    df["bert_pred"] = predictions

In [ ]:
import pandas as pd

#df_brd_sa = pd.read_csv("./analysis_data/Brand Sentiment Analysis Dataset/Dataset - Train.csv")

# read in data after NER csv
df_brd_sa = pd.read_csv("./data after NER.csv")

df_brd_sa.head()

,Unnamed: 0,tweet_text,emotion_in_tweet_is_directed_at,is_there_an_emotion_directed_at_a_brand_or_product,entities
0,0,.@wesley83 I have a 3G iPhone. After 3 hrs twe...,iPhone,Negative emotion,"[{""word"": ""."", ""entity"": ""B-person""}, {""word"":..."
1,1,@jessedee Know about @fludapp ? Awesome iPad/i...,iPad or iPhone App,Positive emotion,"[{""word"": ""@"", ""entity"": ""B-person""}, {""word"":..."
2,2,@swonderlin Can not wait for #iPad 2 also. The...,iPad,Positive emotion,"[{""word"": ""@"", ""entity"": ""B-person""}, {""word"":..."
3,3,@sxsw I hope this year's festival isn't as cra...,iPad or iPhone App,Negative emotion,"[{""word"": ""\u0120festival"", ""entity"": ""B-event..."
4,4,@sxtxstate great stuff on Fri #SXSW: Marissa M...,Google,Positive emotion,"[{""word"": ""xt"", ""entity"": ""I-event""}, {""word"":..."

In [ ]:
df_brd_sa["is_there_an_emotion_directed_at_a_brand_or_product"].unique()

array(['Negative emotion', 'Positive emotion',
       'No emotion toward brand or product', "I can't tell"], dtype=object)

In [ ]:
df_brd_sa.dropna(inplace=True)

In [ ]:
df_brd_sa["sentiment_prediction"] = df_brd_sa["tweet_text"].apply(lambda x: sentiment_score(x[:500], bertweet_t, bertweet))

NameError: name 'sentiment_score' is not defined

In [ ]:
df_brd_sa["sentiment_prediction"].unique()

array([1, 2, 0], dtype=int64)

In [ ]:
# 0 negative
# 1 neutral
# 2 positive
df_brd_sa["sentiment"] = df_brd_sa["is_there_an_emotion_directed_at_a_brand_or_product"].replace({"Negative emotion" : 0, "Positive emotion" : 2, "No emotion toward brand or product" : 1, "I can't tell" : 1})
df_brd_sa.head()

<ipython-input-28-a1d262d7c544>:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_brd_sa["sentiment"] = df_brd_sa["is_there_an_emotion_directed_at_a_brand_or_product"].replace({"Negative emotion" : 0, "Positive emotion" : 2, "No emotion toward brand or product" : 1, "I can't tell" : 1})

,Unnamed: 0,tweet_text,emotion_in_tweet_is_directed_at,is_there_an_emotion_directed_at_a_brand_or_product,entities,sentiment
0,0,.@wesley83 I have a 3G iPhone. After 3 hrs twe...,iPhone,Negative emotion,"[{""word"": ""."", ""entity"": ""B-person""}, {""word"":...",0
1,1,@jessedee Know about @fludapp ? Awesome iPad/i...,iPad or iPhone App,Positive emotion,"[{""word"": ""@"", ""entity"": ""B-person""}, {""word"":...",2
2,2,@swonderlin Can not wait for #iPad 2 also. The...,iPad,Positive emotion,"[{""word"": ""@"", ""entity"": ""B-person""}, {""word"":...",2
3,3,@sxsw I hope this year's festival isn't as cra...,iPad or iPhone App,Negative emotion,"[{""word"": ""\u0120festival"", ""entity"": ""B-event...",0
4,4,@sxtxstate great stuff on Fri #SXSW: Marissa M...,Google,Positive emotion,"[{""word"": ""xt"", ""entity"": ""I-event""}, {""word"":...",2

In [37]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
def performance_metrics(df, label, prediction):
     accuracy = accuracy_score(df[label], df[prediction])
     precision = precision_score(df[label], df[prediction], average="weighted")
     recall = recall_score(df[label], df[prediction], average="weighted")
     f1 = f1_score(df[label], df[prediction], average="weighted")

     print(f"Accuracy: {accuracy}")
     print(f"Precision: {precision}")
     print(f"Recall: {recall}")
     print(f"F1-Score: {f1}")

In [ ]:
performance_metrics(df_brd_sa, "sentiment", "sentiment_prediction")

Accuracy: 0.7289577635976907
Precision: 0.8810658835129812
Recall: 0.7289577635976907
F1-Score: 0.7884397587742731

In [ ]:
df_brd_sa.to_csv("./data after SA.csv")

In [ ]:
bert_pred(bertweet, bertweet_t, df_brd_sa, "tweet_text")

In [ ]:
df_brd_sa.head()

,Unnamed: 0,tweet_text,emotion_in_tweet_is_directed_at,is_there_an_emotion_directed_at_a_brand_or_product,entities,sentiment,bert_pred
0,0,.@wesley83 I have a 3G iPhone. After 3 hrs twe...,iPhone,Negative emotion,"[{""word"": ""."", ""entity"": ""B-person""}, {""word"":...",0,1
1,1,@jessedee Know about @fludapp ? Awesome iPad/i...,iPad or iPhone App,Positive emotion,"[{""word"": ""@"", ""entity"": ""B-person""}, {""word"":...",2,2
2,2,@swonderlin Can not wait for #iPad 2 also. The...,iPad,Positive emotion,"[{""word"": ""@"", ""entity"": ""B-person""}, {""word"":...",2,2
3,3,@sxsw I hope this year's festival isn't as cra...,iPad or iPhone App,Negative emotion,"[{""word"": ""\u0120festival"", ""entity"": ""B-event...",0,1
4,4,@sxtxstate great stuff on Fri #SXSW: Marissa M...,Google,Positive emotion,"[{""word"": ""xt"", ""entity"": ""I-event""}, {""word"":...",2,2

In [ ]:
performance_metrics(df_brd_sa, "sentiment", "bertweet_pred")

Accuracy: 0.7289577635976907
Precision: 0.8810658835129812
Recall: 0.7289577635976907
F1-Score: 0.7884397587742731

## testing with sentiment corpus

In [54]:
import pandas as pd
df_sc = pd.read_json("sentiment_corpus.json", orient="records")
df_sc.head()

                                                text  labels
0  Nun LIVE ▶️ [PC│GER] Bugisoft bestes Spiel Kap...       1
1                                   {{MENTION}} Pick       1
2  ETTelecom | Fake Apple items worth Rs 13.8L se...       0
3  RT {{MENTION}} ⚠️ The affected giants include ...       1
4  Is there any way of deleting an app that won't...       0

In [57]:
bert_pred(bertweet, bertweet_t, df_sc, "text")

model.safetensors:   0%|          | 0.00/540M [00:00<?, ?B/s]

In [58]:
performance_metrics(df_sc, "labels", "bert_pred")

Accuracy: 0.6272260790824027
Precision: 0.6611441262229791
Recall: 0.6272260790824027
F1-Score: 0.6272425239648367

## bertweet fine-tuning

In [ ]:
# trying to fine-tune this model (goal of accuracy > 72,89% and precision > 88,1%)
from datasets import Dataset

dataset = Dataset.from_pandas(df_brd_sa)

In [ ]:
def tokenize_function(example):
    return tokenizer(example['tweet_text'], truncation=True, padding='max_length', max_length=128)

tokenized_datasets = dataset.map(tokenize_function, batched=True)
tokenized_datasets = tokenized_datasets.rename_column('sentiment', 'labels')
tokenized_datasets.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

Map:   0%|          | 0/3291 [00:00<?, ? examples/s]

In [ ]:
train_test_split = tokenized_datasets.train_test_split(test_size=0.2)
train_dataset = train_test_split['train']
test_dataset = train_test_split['test']

In [15]:
from sklearn.metrics import precision_recall_fscore_support, accuracy_score, precision_score

def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='weighted')
    acc = accuracy_score(labels, preds)
    return {"accuracy": acc, "precision": precision, "recall": recall, "f1": f1}

In [ ]:
from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir='./results',
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=4, # adjust depending on resources
    per_device_eval_batch_size=4,
    num_train_epochs=2, # adjust depending on resources
    weight_decay=0.01,
    logging_dir='./logs',
    load_best_model_at_end=True
)

c:\Users\hausb\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

trainer.train()

C:\Users\hausb\AppData\Local\Temp\ipykernel_7652\3252959399.py:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: hausbichler-georg (hausbichler-georg-wirtschaftsuniversit-t-wien). Use `wandb login --relogin` to force relogin

  0%|          | 0/1316 [00:00<?, ?it/s]

{'loss': 0.4696, 'grad_norm': 34.91965103149414, 'learning_rate': 1.2401215805471124e-05, 'epoch': 0.76}

  0%|          | 0/165 [00:00<?, ?it/s]

c:\Users\hausb\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

{'eval_loss': 0.3217962682247162, 'eval_accuracy': 0.9044006069802731, 'eval_precision': 0.8776387724816433, 'eval_recall': 0.9044006069802731, 'eval_f1': 0.8906713195717271, 'eval_runtime': 125.3936, 'eval_samples_per_second': 5.255, 'eval_steps_per_second': 1.316, 'epoch': 1.0}
{'loss': 0.3243, 'grad_norm': 56.448238372802734, 'learning_rate': 4.80243161094225e-06, 'epoch': 1.52}

  0%|          | 0/165 [00:00<?, ?it/s]

c:\Users\hausb\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

{'eval_loss': 0.3860619068145752, 'eval_accuracy': 0.91350531107739, 'eval_precision': 0.8822575684694961, 'eval_recall': 0.91350531107739, 'eval_f1': 0.8969385263946141, 'eval_runtime': 115.0542, 'eval_samples_per_second': 5.728, 'eval_steps_per_second': 1.434, 'epoch': 2.0}
{'train_runtime': 7890.3636, 'train_samples_per_second': 0.667, 'train_steps_per_second': 0.167, 'train_loss': 0.36438215539810503, 'epoch': 2.0}

TrainOutput(global_step=1316, training_loss=0.36438215539810503, metrics={'train_runtime': 7890.3636, 'train_samples_per_second': 0.667, 'train_steps_per_second': 0.167, 'total_flos': 346257257730048.0, 'train_loss': 0.36438215539810503, 'epoch': 2.0})

In [ ]:
results = trainer.evaluate(test_dataset)
print(results)

  0%|          | 0/165 [00:00<?, ?it/s]

c:\Users\hausb\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

{'eval_loss': 0.3217962682247162, 'eval_accuracy': 0.9044006069802731, 'eval_precision': 0.8776387724816433, 'eval_recall': 0.9044006069802731, 'eval_f1': 0.8906713195717271, 'eval_runtime': 114.8893, 'eval_samples_per_second': 5.736, 'eval_steps_per_second': 1.436, 'epoch': 2.0}

In [ ]:
model.save_pretrained('./models/bertweetSA_after_inital_finetuning')
tokenizer.save_pretrained('./models/bertweetSA_after_inital_finetuning')

('./models/bertweetSA_after_inital_finetuning\\tokenizer_config.json',
 './models/bertweetSA_after_inital_finetuning\\special_tokens_map.json',
 './models/bertweetSA_after_inital_finetuning\\vocab.txt',
 './models/bertweetSA_after_inital_finetuning\\bpe.codes',
 './models/bertweetSA_after_inital_finetuning\\added_tokens.json')

# Testing fine-tuned BERTweet-SA

In [ ]:
#loading and trying the saved model
tokenizer2 = AutoTokenizer.from_pretrained("./models/bertweetSA_after_inital_finetuning")

model2 = AutoModelForSequenceClassification.from_pretrained("./models/bertweetSA_after_inital_finetuning")

In [ ]:
df_brd_sa["sentiment_prediction_finetuned"] = df_brd_sa["tweet_text"].apply(lambda x: sentiment_score(x[:500], tokenizer2, model2))

In [ ]:
# very high results, but may not be too telling because it was tested on same data it was finetuned on
performance_metrics(df_brd_sa, "sentiment", "sentiment_prediction_finetuned")

Accuracy: 0.9310240048617442
Precision: 0.9037352697049685
Recall: 0.9310240048617442
F1-Score: 0.9170998038436116

c:\Users\hausb\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

## preprocessing Tweets Big Tech data

In [ ]:
import pandas as pd
df_tweets_bigtech_10ksample = pd.read_csv("tweets_bigtech_10ksample.csv")

In [ ]:
# creating small test dataset with random sampling for later
df_tweets_bigtech_test = df_tweets_bigtech.sample(n=4000, seed=42)
df_tweets_bigtech_test.to_csv("./tweets_bigtech_test.csv")

In [ ]:
df_tweets_bigtech_10ksample["sentiment_prediction_finetuned"] = df_tweets_bigtech_10ksample["text"].apply(lambda x: sentiment_score(x[:500], tokenizer2, model2))

In [ ]:
df_tweets_bigtech_10ksample.head()

,created_at,file_name,followers,friends,group_name,location,retweet_count,screenname,search_query,text,twitter_id,username,polarity,partition_0,partition_1,sentiment,sentiment_prediction_finetuned
0,2020-07-12 09:24:26,AMD,25,114,AMD,United Kingdom,0.0,moffphcgaming,#AMD,Been on holiday so back now. Gonna try get som...,1.282244e+18,🕹MoffPHC Gaming🕹,-0.3102,Technology,AMD,0,2
1,2020-07-12 08:16:45,AMD,1719,1,AMD,digitalocean,1.0,LinuxDreams,#AMD,RT @LinuxReviews: #Linux architect Linus Torva...,1.282227e+18,LinuxDreams,-0.3612,Technology,AMD,0,0
2,2020-07-12 08:11:41,AMD,69,135,AMD,Amsterdam,1.0,LinuxReviews,#AMD,"#Linux architect Linus Torvalds: AVX512 Is ""A ...",1.282226e+18,LinuxReviews,-0.3612,Technology,AMD,0,0
3,2020-07-12 02:22:50,AMD,34,155,AMD,San Francisco,0.0,NdrewGarcia,#AMD,#AMD stuck in a range box chart https://t.co/5...,1.282138e+18,Encino_Man,-0.2500,Technology,AMD,0,0
4,2020-07-11 23:58:44,AMD,802,730,AMD,"New Jersey, USA",0.0,Roger_Clinton1,#AMD,$AMD Epyc Milan Leak – Three early Genesis sam...,1.282102e+18,Roger Ocasio-Clinton,-0.3400,Technology,AMD,0,2

In [ ]:
performance_metrics(df_tweets_bigtech_10ksample, "sentiment", "sentiment_prediction_finetuned")

Accuracy: 0.5633684210526316
Precision: 0.5890056459480304
Recall: 0.5633684210526316
F1-Score: 0.48415694314369734

In [ ]:
# comparison with not fine-tuned model on tweets-bigtech-data
df_tweets_bigtech_10ksample["sentiment_prediction"] = df_tweets_bigtech_10ksample["text"].apply(lambda x: sentiment_score(x[:500], tokenizer, model))

In [ ]:
performance_metrics(df_tweets_bigtech_10ksample, "sentiment", "sentiment_prediction")

Accuracy: 0.5675789473684211
Precision: 0.6583776609118885
Recall: 0.5675789473684211
F1-Score: 0.5742206759300184

# Second Fine-tuning of BERTweet-SA with new data

In [ ]:
# finetuning on tweets_bigtech_10ksample
import pandas as pd
df_tweets_bigtech_10ksample = pd.read_csv("./tweets_bigtech_10ksample.csv")
df_tweets_bigtech_10ksample.head()

,Unnamed: 0,created_at,file_name,followers,friends,group_name,location,retweet_count,screenname,search_query,text,twitter_id,username,polarity,partition_0,partition_1,sentiment
0,0,2020-07-12 09:24:26,AMD,25,114,AMD,United Kingdom,0.0,moffphcgaming,#AMD,Been on holiday so back now. Gonna try get som...,1.282244e+18,🕹MoffPHC Gaming🕹,-0.3102,Technology,AMD,0
1,1,2020-07-12 08:16:45,AMD,1719,1,AMD,digitalocean,1.0,LinuxDreams,#AMD,RT @LinuxReviews: #Linux architect Linus Torva...,1.282227e+18,LinuxDreams,-0.3612,Technology,AMD,0
2,2,2020-07-12 08:11:41,AMD,69,135,AMD,Amsterdam,1.0,LinuxReviews,#AMD,"#Linux architect Linus Torvalds: AVX512 Is ""A ...",1.282226e+18,LinuxReviews,-0.3612,Technology,AMD,0
3,3,2020-07-12 02:22:50,AMD,34,155,AMD,San Francisco,0.0,NdrewGarcia,#AMD,#AMD stuck in a range box chart https://t.co/5...,1.282138e+18,Encino_Man,-0.2500,Technology,AMD,0
4,4,2020-07-11 23:58:44,AMD,802,730,AMD,"New Jersey, USA",0.0,Roger_Clinton1,#AMD,$AMD Epyc Milan Leak – Three early Genesis sam...,1.282102e+18,Roger Ocasio-Clinton,-0.3400,Technology,AMD,0

In [ ]:
from datasets import Dataset

dataset = Dataset.from_pandas(df_tweets_bigtech_10ksample)

In [ ]:
def tokenize_function(example):
    return tokenizer(example['text'], truncation=True, padding='max_length', max_length=128)

tokenized_datasets = dataset.map(tokenize_function, batched=True)
tokenized_datasets = tokenized_datasets.rename_column('sentiment', 'labels')
tokenized_datasets.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

Map:   0%|          | 0/9500 [00:00<?, ? examples/s]

In [ ]:
train_test_split = tokenized_datasets.train_test_split(test_size=0.2)
train_dataset = train_test_split['train']
test_dataset = train_test_split['test']

In [ ]:
from sklearn.metrics import precision_recall_fscore_support, accuracy_score, precision_score

def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='weighted')
    acc = accuracy_score(labels, preds)
    return {"accuracy": acc, "precision": precision, "recall": recall, "f1": f1}

In [ ]:
from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir='./results',
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8, # adjust depending on resources
    per_device_eval_batch_size=8,
    num_train_epochs=4, # adjust depending on resources
    weight_decay=0.01,
    logging_dir='./logs',
    load_best_model_at_end=True
)

/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

trainer.train()

<ipython-input-22-b292458b8898>:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

TrainOutput(global_step=3800, training_loss=0.2288587941621479, metrics={'train_runtime': 525.1688, 'train_samples_per_second': 57.886, 'train_steps_per_second': 7.236, 'total_flos': 1999661974732800.0, 'train_loss': 0.2288587941621479, 'epoch': 4.0})

In [ ]:
# validation loss increasing after second epoch -> another fine-tuning with only two epochs
trainer.evaluate()

{'eval_loss': 0.3686022162437439,
 'eval_accuracy': 0.9142105263157895,
 'eval_precision': 0.9159459101284247,
 'eval_recall': 0.9142105263157895,
 'eval_f1': 0.9134333434418133,
 'eval_runtime': 6.6617,
 'eval_samples_per_second': 285.214,
 'eval_steps_per_second': 35.727,
 'epoch': 4.0}

In [ ]:
from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir='./results',
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16, # adjust depending on resources
    per_device_eval_batch_size=16,
    num_train_epochs=2, # adjust depending on resources
    weight_decay=0.01,
    logging_dir='./logs',
    load_best_model_at_end=True
)

/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

trainer.train()

<ipython-input-35-b292458b8898>:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

TrainOutput(global_step=950, training_loss=0.3481455752724095, metrics={'train_runtime': 203.2829, 'train_samples_per_second': 74.773, 'train_steps_per_second': 4.673, 'total_flos': 999830987366400.0, 'train_loss': 0.3481455752724095, 'epoch': 2.0})

In [ ]:
trainer.evaluate(eval_dataset=test_dataset)

{'eval_loss': 0.34585440158843994,
 'eval_accuracy': 0.9021052631578947,
 'eval_precision': 0.901972325838357,
 'eval_recall': 0.9021052631578947,
 'eval_f1': 0.9018111448193392,
 'eval_runtime': 6.0186,
 'eval_samples_per_second': 315.69,
 'eval_steps_per_second': 19.772,
 'epoch': 2.0}

In [ ]:
trainer.save_model("./models/bertweet-sa-after-tweetsbigtech")
tokenizer.save_pretrained("./models/bertweet-sa-after-tweetsbigtech")

('./models/bertweet-sa-after-tweetsbigtech/tokenizer_config.json',
 './models/bertweet-sa-after-tweetsbigtech/special_tokens_map.json',
 './models/bertweet-sa-after-tweetsbigtech/vocab.txt',
 './models/bertweet-sa-after-tweetsbigtech/bpe.codes',
 './models/bertweet-sa-after-tweetsbigtech/added_tokens.json')

In [ ]:
model_after_tweetsbigtech = AutoModelForSequenceClassification.from_pretrained("./models/bertweet-sa-after-tweetsbigtech")
tokenizer_after_tweetsbigtech = AutoTokenizer.from_pretrained("./models/bertweet-sa-after-tweetsbigtech")

In [ ]:
df_tweets_bigtech_test = pd.read_csv("./tweets_bigtech_test.csv")
df_tweets_bigtech_test.head()

,Unnamed: 0,created_at,file_name,followers,friends,group_name,location,retweet_count,screenname,search_query,text,twitter_id,username,polarity,partition_0,partition_1,sentiment
0,266816,2020-07-17 20:33:44,Apple,57,169,Apple,Bruxelles - Luxembourg,0.0,realSebThomas,#Apple OR #Iphone,2 days after the #Apple #Stateaid judgment of ...,1.284225e+18,Sébastien Thomas,0.0,Technology,Apple,1
1,259583,2020-07-17 12:39:25,Apple,6,89,Apple,Australia,235.0,holycrapps,#Apple OR #Iphone,RT @GFSquad__com: [PIC] 200717- @GFRDofficial ...,1.284105e+18,『 』,0.0,Technology,Apple,1
2,434342,2020-08-10 11:21:00,Twitch,134,142,Twitch,Leeds,2.0,FarrerArt,#Twitch,✨✍🏻💫MEET THE ARTIST &amp; SUB SKETCHES💫✍🏻✨ St...,1.292783e+18,Farrer Art,0.0,Technology,Twitch,1
3,144183,2020-07-12 08:58:23,Netflix,279,323,Netflix,ur heart,102.0,apphiashohe,#Netflix,RT @nakulnarayanak: To the casting director of...,1.282238e+18,a 🦋,0.0,Technology,Netflix,1
4,191249,2020-07-28 22:45:49,Google,198,117,Google,Northern California,0.0,rdmind,#Google,RDM Industrial Products Inc on #Google https:/...,1.288244e+18,RDM Industrial Prod.,0.0,Technology,Google,1

In [ ]:
import torch

def sentiment_score(text, tokenizer, model):
    tokens = tokenizer.encode(text, return_tensors='pt', truncation = True, padding="max_length") #max_length=128 necessary?
    result = model(tokens)
    return int(torch.argmax(result.logits))

In [ ]:
df_tweets_bigtech_test["sentiment_prediction_finetuned"] = df_tweets_bigtech_test["text"].apply(lambda x: sentiment_score(x[:500], tokenizer_after_tweetsbigtech, model_after_tweetsbigtech))

We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.

In [ ]:
performance_metrics(df_tweets_bigtech_test, "sentiment", "sentiment_prediction_finetuned")

Accuracy: 0.5525
Precision: 0.6684950730088312
Recall: 0.5525
F1-Score: 0.5044394096592938

#fine-tuning Bert-base-uncased with tweets bigtech

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
bert_base_t = AutoTokenizer.from_pretrained("google-bert/bert-base-uncased")

bert_base = AutoModelForSequenceClassification.from_pretrained(
    "google-bert/bert-base-uncased",
    num_labels=3)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
# using 25k rows of Tweets-BigTech-data to finetune
import pandas as pd
df_tweets_bigtech_25ksample = pd.read_csv("./tweets_bigtech_25ksample.csv")
df_tweets_bigtech_25ksample.head()

,Unnamed: 0,created_at,file_name,followers,friends,group_name,location,retweet_count,screenname,search_query,text,twitter_id,username,polarity,partition_0,partition_1,sentiment
0,0,2020-07-12 09:24:26,AMD,25,114,AMD,United Kingdom,0.0,moffphcgaming,#AMD,Been on holiday so back now. Gonna try get som...,1.282244e+18,🕹MoffPHC Gaming🕹,-0.3102,Technology,AMD,0
1,1,2020-07-12 08:16:45,AMD,1719,1,AMD,digitalocean,1.0,LinuxDreams,#AMD,RT @LinuxReviews: #Linux architect Linus Torva...,1.282227e+18,LinuxDreams,-0.3612,Technology,AMD,0
2,2,2020-07-12 08:11:41,AMD,69,135,AMD,Amsterdam,1.0,LinuxReviews,#AMD,"#Linux architect Linus Torvalds: AVX512 Is ""A ...",1.282226e+18,LinuxReviews,-0.3612,Technology,AMD,0
3,3,2020-07-12 02:22:50,AMD,34,155,AMD,San Francisco,0.0,NdrewGarcia,#AMD,#AMD stuck in a range box chart https://t.co/5...,1.282138e+18,Encino_Man,-0.2500,Technology,AMD,0
4,4,2020-07-11 23:58:44,AMD,802,730,AMD,"New Jersey, USA",0.0,Roger_Clinton1,#AMD,$AMD Epyc Milan Leak – Three early Genesis sam...,1.282102e+18,Roger Ocasio-Clinton,-0.3400,Technology,AMD,0

In [ ]:
from datasets import Dataset

dataset = Dataset.from_pandas(df_tweets_bigtech_25ksample)

In [ ]:
def tokenize_function(example):
    return bert_base_t(example['text'], truncation=True, padding='max_length', max_length=128)

tokenized_dataset = dataset.map(tokenize_function, batched=True)
tokenized_dataset = tokenized_dataset.rename_column('sentiment', 'labels')
tokenized_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

In [ ]:
train_test_split1 = tokenized_dataset.train_test_split(test_size=0.2, seed=42)
train_val_dataset = train_test_split1['train']
test_dataset = train_test_split1['test']

train_test_split2 = train_val_dataset.train_test_split(test_size=0.2, seed=42)
train_dataset = train_test_split2['train']
val_dataset = train_test_split2['test']

In [ ]:
from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir='./bert-base-uncased-sa',
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=32, # adjust depending on resources
    per_device_eval_batch_size=32,
    num_train_epochs=2, # adjust depending on resources
    weight_decay=0.01,
    logging_dir='./logs',
    load_best_model_at_end=True
)

trainer = Trainer(
    model=bert_base,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    tokenizer=bert_base_t,
    compute_metrics=compute_metrics
)

/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
<ipython-input-34-d3be35ee8fd1>:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [ ]:
trainer.train()

TrainOutput(global_step=1000, training_loss=0.27716554260253906, metrics={'train_runtime': 348.0426, 'train_samples_per_second': 91.943, 'train_steps_per_second': 2.873, 'total_flos': 2104907341824000.0, 'train_loss': 0.27716554260253906, 'epoch': 2.0})

In [ ]:
trainer.evaluate(test_dataset)

{'eval_loss': 0.28531941771507263,
 'eval_accuracy': 0.9118,
 'eval_precision': 0.9119073638565798,
 'eval_recall': 0.9118,
 'eval_f1': 0.9116519515593955,
 'eval_runtime': 16.3735,
 'eval_samples_per_second': 305.372,
 'eval_steps_per_second': 9.589,
 'epoch': 2.0}

In [ ]:
bert_base.save_pretrained("bert-base-uncased-sa")
bert_base_t.save_pretrained("bert-base-uncased-sa")

('bert-base-uncased-sa/tokenizer_config.json',
 'bert-base-uncased-sa/special_tokens_map.json',
 'bert-base-uncased-sa/vocab.txt',
 'bert-base-uncased-sa/added_tokens.json',
 'bert-base-uncased-sa/tokenizer.json')

## applying the model

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
bert_base_ft_t = AutoTokenizer.from_pretrained("bert-base-uncased-sa")

bert_base_ft = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased-sa",
    num_labels=3)

In [ ]:
df_tweets_bigtech_test = test_dataset.to_pandas()
df_tweets_bigtech_test.head()

,Unnamed: 0,created_at,file_name,followers,friends,group_name,location,retweet_count,screenname,search_query,text,twitter_id,username,polarity,partition_0,partition_1,labels,input_ids,token_type_ids,attention_mask
0,19923,2020-07-18 00:12:32,Amazon,394,169,Amazon,"Hartford, CT",1.0,meetKushan,#Amazon OR #AWS,Amazon CloudFront announces new TLS1.2 securit...,1.284280e+18,Kushan,0.4767,Technology,Amazon,2,"[101, 9733, 6112, 12792, 17472, 2047, 1056, 48...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,18453,2020-07-12 04:16:01,Microsoft,5966,2315,Microsoft,Planet Earth,0.0,crpietschmann,#Microsoft,Top 11 #AzureIoT Announcements from Build 2020...,1.282167e+18,Chris Pietschmann,0.2023,Technology,Microsoft,2,"[101, 2327, 2340, 1001, 24296, 25185, 25674, 2...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,12236,2020-07-08 21:38:05,Microsoft,2513,0,Microsoft,Raspberry Pi,2.0,LlnuxBot,#Microsoft,"RT @techdudeinc: via #BleepingComputer Blog: ""...",1.280979e+18,LinuxBot,0.0000,Technology,Microsoft,1,"[101, 19387, 1030, 6627, 8566, 3207, 2378, 227...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,16941,2020-07-09 04:58:01,Tesla,400,677,Tesla,United Kingdom,4.0,appthisway,#Tesla,RT @mvollmer1: Here are six reasons why #hydro...,1.281090e+18,Appthisway®,0.5719,Technology,Tesla,2,"[101, 19387, 1030, 19842, 14511, 5017, 2487, 1...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,8218,2020-08-29 15:37:00,Apple,544,356,Apple,"Kansas, USA",1.0,DuncsUnlimited,#Apple OR #Iphone,Episode 2 is here - special guest Race Car Dri...,1.299733e+18,delly,-0.2942,Technology,Apple,0,"[101, 2792, 1016, 2003, 2182, 1011, 2569, 4113...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [ ]:
# move model parameters to GPU if not loaded correctly
# param_device = next(model.parameters()).device

In [ ]:
bert_pred(bert_base_ft, bert_base_ft_t, df_tweets_bigtech_test, "text")

In [ ]:
performance_metrics(df_tweets_bigtech_test, "labels", "bert_pred")

Accuracy: 0.912
Precision: 0.9121157265185696
Recall: 0.912
F1-Score: 0.9118522077610691

In [ ]:
# also evaluating model on Brand-SA-data
df_brd_sa_p = pd.read_csv("./brand_sentiment_analysis_preprocessed.csv")
df_brd_sa_p.head()

,tweet_text,is_there_an_emotion_directed_at_a_brand_or_product,sentiment
0,.@wesley83 I have a 3G iPhone. After 3 hrs twe...,Negative emotion,0
1,@jessedee Know about {@fludapp@} ? Awesome iPa...,Positive emotion,2
2,@swonderlin Can not wait for #iPad 2 also. The...,Positive emotion,2
3,@sxsw I hope this year's festival isn't as cra...,Negative emotion,0
4,@sxtxstate great stuff on Fri #SXSW: Marissa M...,Positive emotion,2

In [ ]:
bert_pred(bert_base_ft, bert_base_ft_t, df_brd_sa_p, "tweet_text")

In [ ]:
performance_metrics(df_brd_sa_p, "sentiment", "bert_pred")

Accuracy: 0.5525151374010246
Precision: 0.6335749784291748
Recall: 0.5525151374010246
F1-Score: 0.5743773762349313

In [ ]:
# testing with Tweets Sentiment Classification data (only negative and positive)
df_tweets_sc = pd.read_csv("./tweets_sentiment_classification_preprocessed.csv")
df_tweets_sc.head()

   label                                              tweet
0      0  #fingerprint #Pregnancy Test {{URL}} #android ...
1      0  Finally a transparant silicon case ^^ Thanks t...
2      0  We love this! Would you go? #talk #makememorie...
3      0  I'm wired I know I'm George I was made that wa...
4      2  What amazing service! Apple won't even talk to...

In [ ]:
bert_pred(bert_base_ft, bert_base_ft_t, df_tweets_sc, "tweet")

In [ ]:
performance_metrics(df_tweets_sc, "label", "bert_pred")

Accuracy: 0.12121212121212122
Precision: 0.2681728937897897
Recall: 0.12121212121212122
F1-Score: 0.15126459593881567

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
# performance for posts where model didnt predict neutral
df_tweets_sc_np = df_tweets_sc[df_tweets_sc["bert_pred"] != 1]
performance_metrics(df_tweets_sc_np, "label", "bert_pred")

Accuracy: 0.21080368906455862
Precision: 0.25069564105360503
Recall: 0.21080368906455862
F1-Score: 0.2176650264958071

# fine-tuning bert base uncased with corpus

In [19]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
bert_base_t = AutoTokenizer.from_pretrained("google-bert/bert-base-uncased")

bert_base = AutoModelForSequenceClassification.from_pretrained(
    "google-bert/bert-base-uncased",
    num_labels=3)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [20]:
import pandas as pd
df_sc = pd.read_json("sentiment_corpus.json", orient="records")
df_sc.head()

                                                text  labels
0  Nun LIVE ▶️ [PC│GER] Bugisoft bestes Spiel Kap...       1
1                                   {{MENTION}} Pick       1
2  ETTelecom | Fake Apple items worth Rs 13.8L se...       0
3  RT {{MENTION}} ⚠️ The affected giants include ...       1
4  Is there any way of deleting an app that won't...       0

In [21]:
from datasets import Dataset

dataset = Dataset.from_pandas(df_sc)

In [22]:
def tokenize_function(example):
    return bert_base_t(example['text'], truncation=True, padding='max_length', max_length=512)

tokenized_dataset = dataset.map(tokenize_function, batched=True)
tokenized_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

Map:   0%|          | 0/19878 [00:00<?, ? examples/s]

In [23]:
train_test_split1 = tokenized_dataset.train_test_split(test_size=0.2, seed=42)
train_val_dataset = train_test_split1['train']
test_dataset = train_test_split1['test']

train_test_split2 = train_val_dataset.train_test_split(test_size=0.2, seed=42)
train_dataset = train_test_split2['train']
val_dataset = train_test_split2['test']

In [27]:
from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir='./bert-base-uncased-sa',
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=32, # adjust depending on resources
    per_device_eval_batch_size=32,
    num_train_epochs=2, # adjust depending on resources
    weight_decay=0.01,
    logging_dir='./logs',
    load_best_model_at_end=True
)

trainer = Trainer(
    model=bert_base,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=bert_base_t,
    compute_metrics=compute_metrics
)

/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
<ipython-input-27-8ca49630181c>:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [28]:
trainer.train()

TrainOutput(global_step=796, training_loss=0.24310749859067063, metrics={'train_runtime': 1057.3314, 'train_samples_per_second': 24.062, 'train_steps_per_second': 0.753, 'total_flos': 6694131573835776.0, 'train_loss': 0.24310749859067063, 'epoch': 2.0})

In [29]:
trainer.evaluate(test_dataset)

{'eval_loss': 0.6098513007164001,
 'eval_accuracy': 0.7965291750503019,
 'eval_precision': 0.7986248172846812,
 'eval_recall': 0.7965291750503019,
 'eval_f1': 0.7955255622161136,
 'eval_runtime': 56.6535,
 'eval_samples_per_second': 70.181,
 'eval_steps_per_second': 2.206,
 'epoch': 2.0}

In [32]:
bert_base.save_pretrained("bert-base-sentiment-corpus")
bert_base_t.save_pretrained("bert-base-sentiment-corpus")

('bert-base-sentiment-corpus/tokenizer_config.json',
 'bert-base-sentiment-corpus/special_tokens_map.json',
 'bert-base-sentiment-corpus/vocab.txt',
 'bert-base-sentiment-corpus/added_tokens.json',
 'bert-base-sentiment-corpus/tokenizer.json')

## applying the model

In [45]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

bert_base_corpus_t = AutoTokenizer.from_pretrained("bert-base-sentiment-corpus")

bert_base_corpus = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-sentiment-corpus",
    num_labels=3)

In [46]:
param_device = next(bert_base_corpus.parameters()).device

In [47]:
df_corpus_test = test_dataset.to_pandas()

In [51]:
import torch

# version where tokenization happens at CPU and prediction on GPU,
# bert tokenizer cant be moved to GPU
def bert_pred(model, tokenizer, df, text_col):
    # moving model to GPU and setting it to evaluation-mode
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    model.eval()

    batch_size = 32
    num_batches = len(df) // batch_size + 1
    predictions = []

    for i in range(num_batches):
        start_idx = i * batch_size
        end_idx = min((i + 1) * batch_size, len(df))
        batch_texts = df[text_col][start_idx:end_idx].tolist()

        batch_tokens = tokenizer(batch_texts, padding=True, truncation=True, return_tensors="pt")
        batch_tokens = {key: value.to(device) for key, value in batch_tokens.items()}

        with torch.no_grad():
            outputs = model(**batch_tokens)
            batch_predictions = torch.argmax(outputs.logits, dim=-1)
            predictions.extend(batch_predictions.cpu().numpy())

    df["bert_pred"] = predictions

In [52]:
bert_pred(bert_base_corpus, bert_base_corpus_t, df_corpus_test, "text")

In [53]:
performance_metrics(df_corpus_test, "labels", "bert_pred")

Accuracy: 0.7965291750503019
Precision: 0.7986248172846812
Recall: 0.7965291750503019
F1-Score: 0.7955255622161136